/**
 * Wave 11A — Structured ingredient row for a meal template.
 * `state` distinguishes raw vs cooked grammage (Vertex prompt asks for `cru`
 * by default since most users weigh ingredients before cooking).
 * Macros (kcal, p, c, f) are per the `grams` quantity, not per 100g.
 */
export interface PlanMealItem {
  food: string;
  grams: number;
  state?: 'cru' | 'cuit';
  kcal: number;
  p: number;
  c: number;
  f: number;
}

export interface PlanMealTemplate {
  name: string;
  description: string;
  approx_kcal: number;
  /**
   * Wave 11A — Detailed list of ingredients with grammage + per-item macros.
   * Optional for back-compat with plans generated before this extension —
   * UI components must gracefully degrade to `description` text when absent.
   */
  items?: PlanMealItem[];
  /**
   * Wave 11A — Total macros for the meal (sum of items[].p/c/f). Optional
   * for back-compat. When present, prefer over the recipe-database fallback.
   */
  macros?: {
    p: number;
    c: number;
    f: number;
  };
}

export interface PlanExercise {
  name: string;
  sets: number;
  reps: string;
  rest_seconds: number;
  /**
   * Wave 7 #8 — Optional superset grouping. Exercises with the same string id
   * (e.g. "A", "B", "C") are performed back-to-back without rest, then the
   * `rest_seconds` of the LAST member applies between rounds.
   * Used by /api/sessions/start to compute block_code A1/A2/B1/B2 instead
   * of the naive paires-de-2 fallback.
   */
  superset_group?: string;
}

export interface PlanTrainingSession {
  name: string;
  frequency_weekly: number;
  exercises: PlanExercise[];
}

export interface PlanDoc {
  id?: string;
  active: boolean;
  date_start: string; // YYYY-MM-DD
  date_end?: string; // YYYY-MM-DD
  kcal: number;
  macros: {
    p: number; // protein
    c: number; // carbs
    f: number; // fat
  };
  meals_template: PlanMealTemplate[];
  training: {
    sessions: PlanTrainingSession[];
  };
  cardio: {
    type: string;
    duration_minutes: number;
    frequency_weekly: number;
    intensity: 'basse' | 'modérée' | 'haute';
  };
  supplements: Array<{
    name: string;
    dosage: string;
    timing: string;
  }>;
  lifestyle_notes: string;
  /**
   * Provenance of the plan. `'ai'` = generated by /api/ai/generate-plan;
   * `'manual'` = user-edited (legacy); `'ai+coach_patched'` = generated by AI
   * then modified via <COACH_PLAN_PATCH> at least once (Wave 6A).
   */
  source: 'ai' | 'manual' | 'ai+coach_patched';
  justification: string;
  created_at: string; // ISO string
  /** Wave 6A — set by /api/coach/apply-patch on each patch */
  last_patched_at?: string;
  last_patched_by?: 'coach' | 'user' | 'system';
}
